services:
  - type: web
    name: fake-news-detector
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0