services:
  - type: web
    name: fake-news-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.py:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 